jobs:
  coverage:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: produce coverage
          command: npm run coveralls
  release:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: build
          command: npm run build
      - run:
          name: release
          command: npm run semantic-release || true
orbs:
  node: circleci/node@2.0.1
version: 2.1
workflows:
  test-and-release:
    jobs:
      - coverage
      - release:
          requires:
            - coverage
